### ISSUE TITLE
Being blasted on a log doesn't killing you

### ISSUE THREAD

**Issue by lordmauve** [larryhastings/pyweek26#20]
Being blasted on a log should kill you, but doesnt.

I just fixed this (hastily) for Dams, but this should be fixed using a refactor and a common base class.

**Comment by larryhastings** [comment]
I just checked in a "src/levels/death.txt" , so you can test with
    % ./game.py death

I tested coverage of all these combinations.

While
 * standing on a timed bomb,
 * standing on a contact bomb,
 * standing on an RC bomb,
 * standing on a freeze bomb,
 * standing on a log,
 * standing on grass,
I was 
    * blasted by a timed bomb, RC bomb, and/or contact bomb
    * frozen by a freeze bomb
which was
  * floating.
  * on grass.

In all those circumstances, Ranger Jim was blasted or frozen as appropriate.

I didn't test *all* possible combinations, since it's the same method call (on_blasted) for all three explosive bombs.  So I'm pretty confident all those bombs would blast you in all those circumstances.  And some of those possible combinations are impractical to test (e.g. standing on a freeze bomb and being blasted by a timed bomb).

**Comment by larryhastings** [comment]
Fixed in 4d0e3d9bbdd54e1b0be15406ccdd79bde65f6991.  Reopen if you're still seeing it.
